ARG ARCH=
FROM ${ARCH}ubuntu:18.04

ENV DEBIAN_FRONTEND="noninteractive"
ENV TZ="America/New_York"

RUN apt update && apt install -y \
  file \
  gcc \
  git \
  make \
&& rm -rf /var/lib/apt/lists/*
  
RUN useradd -m -d /opt/builder builder

WORKDIR /opt/builder
