name: Build
on:
  push:
  pull_request:
    branches:
      - 'main'
      - 'release/*'

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    env:
        REGISTRY: ghcr.io
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Tag Info
        run: git fetch --prune --unshallow

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Test
        run: make

      - name: Build Container Image
        run: |
          set -x
          DEFAULT=main
          if egrep -i "^refs/tags/v[0-9]{1,}\.[0-9]{1,}\.[0-9]{1,}-rc[0-9]{1,}$" <<<$GITHUB_REF >/dev/null; then
            VERSION=${GITHUB_REF##*/v}
          elif egrep -i "^refs/tags/v[0-9]{1,}\.[0-9]{1,}\.[0-9]{1,}$" <<<$GITHUB_REF >/dev/null; then
            TAG=${GITHUB_REF##*/v}
            LATEST=1
          elif egrep -i "^refs/heads/${DEFAULT}$" <<<$GITHUB_REF >/dev/null; then
            VERSION=next
          else
            VERSION=unreleased
          fi
          VERSION=${VERSION,,} # to lowercase
          TAG=${{env.REGISTRY}}/${{github.repository}}
          docker buildx build \
            --tag ${TAG}:${VERSION}-ubuntu \
            --platform linux/amd64,linux/arm64 \
            --build-arg IMAGE=ubuntu:latest \
            --build-arg LIBC=gnu \
            --file .docker/Dockerfile.publish \
            .
          if [ -n "${LATEST}" ]; then
            docker tag ${TAG}:${VERSION}-ubuntu ${TAG}:latest
          fi
          docker buildx build \
            --tag ${TAG}:${VERSION}-alpine \
            --platform linux/amd64,linux/arm64 \
            --build-arg IMAGE=alpine:latest \
            --build-arg LIBC=musl \
            --file .docker/Dockerfile.publish \
            .
          if [ "${VERSION}" != "unreleased" ]; then 
            docker push --all-tags ${TAG}
          fi

