name: Build
on:
  push:
  pull_request:
    branches:
      - 'main'
      - 'release/*'

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    env:
        REGISTRY: ghcr.io
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Tag Info
        run: git fetch --prune --unshallow

#      - name: Build & Test
#        run: make
#
#      - name: Log into the Container Registry
#        if: startsWith(github.ref, 'refs/tags/v')
#        uses: docker/login-action@v1
#        with:
#          #username: ${{secrets.DOCKER_LOGIN}}
#          #password: ${{secrets.DOCKER_TOKEN}}
#          registry: ${{ env.REGISTRY }}
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Image
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          REPO=${{github.repository}}
          echo docker buildx build \
            --tag ${{env.REGISTRY}}/${REPO}:${VERSION} \
            --platform linux/amd64,linux/arm64 \
            --file .docker/Dockerfile.publish \
            .

