name: Build
on:
  push:
  pull_request:
    branches:
      - 'main'
      - 'release/*'

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Get Tag Info
        run: git fetch --prune --unshallow
      - name: Build & Test
        run: make
      - name: Login to Docker Hub
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_LOGIN}}
          password: ${{secrets.DOCKER_TOKEN}}
      - name: Build Image
        #if: startsWith(github.ref, 'refs/tags/v')
        run: |
          TAG=${{secrets.DOCKER_LOGIN}}/${GITHUB_REPOSITORY##*/}:${GITHUB_REF/refs\/tags\/v/}
          echo docker buildx build \
            --tag ${TAG} \
            --platform linux/amd64,linux/arm64 \
            --file .docker/Dockerfile.publish \
            --push \
            .

