name: Build
on:
  push:
  pull_request:
    branches:
      - 'main'
      - 'release/*'

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Get Tag Info
        run: git fetch --prune --unshallow
      - name: Build
        run: make all
      - name: Test
        run: make test
      - name: Save Artifact
        uses: actions/upload-artifact@v2
        with:
          name: binary
          path: eg
          retention-days: 1

  build-arm:
    name: Build & Test on ARM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Get Tag Info
        run: git fetch --prune --unshallow
      - name: Enable Multi-Arch Containers
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - name: Test ARM
        run: docker run --rm -t arm64v8/ubuntu uname -m

  image:
    needs: build
    name: Container Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Get Tag Info
        run: git fetch --prune --unshallow
      - name: Get Artifacts
        uses: actions/download-artifact@v2
        with:
          name: binary
      - name: Build Image
        run: make image
      - name: Login to Docker Hub
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Publish Image
        if: startsWith(github.ref, 'refs/tags/v')
        run: make image-push
