name: Build
on:
  push:
  pull_request:
    branches:
      - 'main'

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
    strategy:
      matrix:
        os: [ubuntu,alpine]
        arch: [amd64,amd64]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Version
        id: version
        uses: battila7/get-version-action@v2

      - name: Get Tag
        id: tag
        run: |
          if [ "true" = "${{ steps.version.outputs.is-semver }}" ]; then
              TAG=${{ steps.version.outputs.version-without-v }}
              echo "::set-output name=latest::true"
              echo "::set-output name=push::true"
          else
            if [ "refs/heads/main" = "${GITHUB_REF}" ]; then
              TAG=next
              echo "::set-output name=push::true"
            else
              TAG=unreleased
            fi
          fi
          echo "::set-output name=tag::${TAG}"

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Builder Image
        run: make builder-os OS=${{ matrix.os }} BUILDER=${{ steps.buildx.output.name }} PUSH=${{ steps.tag.outputs.push }}

      - name: Build & Test
        run: make build-os-arch OS=${{ matrix.os }} ARCH=${{ matrix.arch }}/ VERSION=${{ steps.tag.outputs.tag }}

      - name: Build Container Image
        run: make image-os OS=${{ matrix.os }} VERSION=${{ steps.tag.outputs.tag }} LATEST=${{ steps.tag.outputs.latest }} PUSH=${{ steps.tag.outputs.push }}

